#!/bin/sh
cd ${0%/*} || exit 1			# Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Perform various checks
wmakeCheckPwd "$WM_PROJECT_USER_DIR" || {
	echo "Allwmake error: Current directory is not \$WM_PROJECT_USER_DIR"
	exit 1
}

src/Allwmake $targetType $*
applications/Allwmake $targetType $*
