#!/bin/sh
cd ${0%/*} || exit 1			# Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Perform various checks
wmakeCheckPwd "$WM_PROJECT_USER_DIR/applications" || {
	echo "Allwmake error: Current directory is not \$WM_PROJECT_USER_DIR/src"
	exit 1
}

echo $targetType $*
wmake $targetType solvers/atmBuoyantPimpleFoam
wmake $targetType solvers/atmBuoyantMultiphaseEulerPimpleFoam
wmake $targetType solvers/explicitFoam
