#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Define key parameters
dThetadz=-0.5

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runApplication blockMesh
runApplication decomposePar
for PROC in $(echo processor*)
do
	runApplication -append foamDictionary -entry boundaryField/floor/gradient -set "uniform $dThetadz" \
		$PROC/0/theta
done

runParallel $application
#------------------------------------------------------------------------------
